name: terminal_color_parser
description: Parse terminal colors for displaying in other formats. Supports ANSI and xterm256.
version: 0.7.0
repository: https://github.com/chenasraf/terminal_color_parser_dart

environment:
  sdk: ^2.15.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0

script_runner:
  scripts:
    - publish: dart format .; dart pub publish
