name: terminal_color_parser
description: Parse terminal colors for displaying in other formats. Supports ANSI and xterm256.
version: 0.8.0
repository: https://github.com/chenasraf/terminal_color_parser_dart

environment:
  sdk: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

script_runner:
  scripts:
    - publish: dart format .; dart pub publish
